### ISSUE TITLE
Lower dependabot dependency update rate

### ISSUE THREAD

**Issue by jtec** [jtec/prx#147]
Can we configure dependabot to update dependencies e.g. once per month, to lower the amount of commits on `main`?

**Comment by armallen** [comment]
You can lower that, and also group the dependencies to create one PR for all dependencies to update, 
see documentation [here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups)

and scheduling interval is configured [here](https://github.com/jtec/prx/blob/310261383c81dfc7e82e86ad228697751a9154f6/.github/dependabot.yml#L11)
