### ISSUE TITLE
Position-domain unit test

### ISSUE THREAD

**Issue by jtec** [jtec/prx#42]
Let's add a unit test that

- runs a RINEX observation file through prx
- parses the generated CSV file
- computes the LSQ PVT solution
- compares to the expected solution
  - what would we compare the T to? Clock-steering receiver, so small?

Fancy version: use a station where >= 4 satellites of all constellations are visible (e.g. Japan), parameterize the test with a set of constellations to use and run for 
- all constellations
- each constellation separately

**Comment by plutonheaven** [comment]
I think that we just need to validate the position error. A wrong rx clock estimation would also lead to a wrong error.

If not sure about that, we could remove the receiver clock estimation by using "between satellites single-differenced" observations
