### ISSUE TITLE
Rename parameters computed by PRX

### ISSUE THREAD

**Issue by plutonheaven** [jtec/prx#50]
The name of the parameters computed by PRX should be 
- explicit (to be recognized by someone working on GNSS)
- model-agnostic
- contain the unit

For example, the parameter
- `x_m` is not explicit enough
- `iono_delay_klobuchar_m` is not model-agnostic

**Comment by Shetty1103** [comment]
@jtec How about the following names for certain parameters?
**carrier_iono_delay_klobuchar_m** was suggested to be removed by @plutonheaven 
x_m and dx_mps could be renamed similarly for the y and z components.
C_obs does not seem to have its unit in the present code, it has been included in the table below-

| Proposed Names                   | Existing Names                     |
|------------------------------|---------------------------------|
| sat_clock_offset_m           | clock_m                         |
| sat_clock_drift_mps          | Dclock_mps                      |
| sat_pos_x_m                  | x_m                             |
| sat_vel_x_mps                | dx_mps                          |
| sat_instrumental_delay_m     | group delay_m                   |
| iono_delay_m                 | code_iono_delay_klobuchar_m    |
| sat_elevation_deg            | elevation_deg                   |
| sat_azim_deg                 | azimuth_deg                     |
| rnx_obs_identifier           | observation_code                |
| C_obs_m                      | C_obs                           |
