### ISSUE TITLE
User-provided RNX NAV file

### ISSUE THREAD

**Issue by plutonheaven** [jtec/prx#83]
It may be interesting to let the user provide the NAV file together with the OBS file, e.g. to verify time to first fix in a constrained environment leading to difficulty to demodulate the Navigation Messages.

PRX currently download the NAV files from IGS servers, and therefore has always access to well-formatted files. Letting users provide their own files may break a few assumptions that we are making by using IGS files.

If we let other NAV files possible, careful check should be performed, for example by running additional options with `gfzrnx`.

**Comment by jtec** [comment]
Is the case on master, see https://github.com/jtec/prx/blob/416e969ad6132c1e33c9dfe6100fd3133513743f/src/prx/rinex_nav/nav_file_discovery.py#L161
